<a href="https://colab.research.google.com/github/Sophiajackrich/Stutern-repo/blob/main/Sophia's_Assignment_3(Numpy_pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 3 (Week 3)

>**Note**: Late submissions are ***`penalized`***.

## Name: JACKRICH SOPHIA

<br>

### Please show and display all your calculations and results.

In [2]:
from google.colab import drive
#drive.mount('/content/drive')

In [1]:
!pip install nb_black

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 20.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 10.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 59.6 MB/s eta 0:00:00
  Created wheel for nb_black: filename=nb_black-1.0.7-py3-none-any.whl size=5298 sha256=28fce1dc16210aa96c06b4633e3a77908c14196a43839b7aa5195b7b3b44ec69
  Stored in directory: /root/.cache/pip/wheels/a6/5e/1e/a15614d6ea220d070043db3b650d73a8b4938aefd520496c11
Successfully built nb_black
  Attempting uninstall: click
    Found existing installation: click 7.1.2
    Uninstalling click-7.1.2:
      Successfully uninstalled click-7.1.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 1.1.

In [2]:
# Standard imports
import numpy as np
import pandas as pd

# pandas settings
pd.options.display.max_rows = 1_000
pd.options.display.max_columns = 1_000
pd.options.display.max_colwidth = 1_000

# Black code formatter (Optional)
%load_ext lab_black

In [3]:
def show_array_properties(*, arr: np.ndarray) -> None:
    """This returns the ndarray, shape, number of
    dimensions and the size of the input array.

    Params:
        arr: The ndarray (NumPy array)

    Returns:
        None
    """
    print(
        f"Array: \n{arr}\n"
        f"\nShape: {arr.shape}"
        f"\nNDim: {arr.ndim}"
        f"\nSize: {arr.size}"
    )

## Qs 1

**a.** Given that 

```python
x = np.linspace(0, 10, 10001)
```

using **ONLY** `NumPy`, write an equation that calculates `y`. `y` is calculated using the equation below:
 
$$
y = \exp^{(\frac{-x}{10})}*\sin{(x)}
$$

<br>

**b.** Write a NumPy code that calculates: 

$$
result = \frac{\sum{((x - \bar{x}) * (y - \bar{y}))}}{\sum{(x - \bar{x})^2}}
$$


`X` and `y` are given below:

```python
rng = np.random.default_rng(seed=5)
X = rng.random(size=(35, 2), dtype=np.float32)
y = rng.random(size=(35, 1), dtype=np.float32)
```

In [ ]:
# Write your solution here
# Qs 1a: Showing the properties of question 1a
x = np.linspace(0, 10, 10001)
show_array_properties(arr=x)

# Solution
step_1 =  np.square(-x/10)
step_2 = np.sin(x)
# final step
y = np.exp(np.square(-x/10)) * np.sin(x)
print("The solution for question 1a is:", y)


Array: 
[0.000e+00 1.000e-03 2.000e-03 ... 9.998e+00 9.999e+00 1.000e+01]

Shape: (10001,)
NDim: 1
Size: 10001
The solution for question 1a is: [ 0.00000000e+00  9.99999843e-04  1.99999875e-03 ... -1.47364856e+00
 -1.47622587e+00 -1.47880270e+00]


In [ ]:
# Write your solution here
# Qs 1b
# reading out the data
rng = np.random.default_rng(seed=5)
X = rng.random(size=(35, 2), dtype=np.float32)
y = rng.random(size=(35, 1), dtype=np.float32)
# checking properties of the X and y array
show_array_properties(arr=X)
show_array_properties(arr=y)

Array: 
[[0.67079    0.80500287]
 [0.02265316 0.8079408 ]
 [0.46885186 0.51532555]
 [0.630234   0.28580135]
 [0.97952366 0.0539307 ]
 [0.2779237  0.38336885]
 [0.57118434 0.4084732 ]
 [0.1310609  0.04527515]
 [0.00101531 0.04875767]
 [0.14881468 0.9991761 ]
 [0.19098222 0.6523691 ]
 [0.75025886 0.23451018]
 [0.28223735 0.43494755]
 [0.2632376  0.9741862 ]
 [0.1777215  0.8976776 ]
 [0.7976888  0.844231  ]
 [0.11573023 0.39240462]
 [0.62803024 0.49302298]
 [0.66586643 0.6766893 ]
 [0.6629264  0.0608027 ]
 [0.95909935 0.5555961 ]
 [0.90351176 0.2714516 ]
 [0.3615182  0.8796511 ]
 [0.18690258 0.06421441]
 [0.3739066  0.6791815 ]
 [0.12224686 0.87008846]
 [0.34105366 0.22731847]
 [0.5444494  0.8954482 ]
 [0.88393277 0.8721954 ]
 [0.30646878 0.0185172 ]
 [0.77814275 0.7074955 ]
 [0.77097714 0.00119966]
 [0.03785986 0.5033639 ]
 [0.33515435 0.43666703]
 [0.9313037  0.20325279]]

Shape: (35, 2)
NDim: 2
Size: 70
Array: 
[[0.52798015]
 [0.3249426 ]
 [0.2949664 ]
 [0.8062153 ]
 [0.15321892]
 [0.3


$$
result = \frac{\sum{((x - \bar{x}) * (y - \bar{y}))}}{\sum{(x - \bar{x})^2}}
$$

In [ ]:
# Getting the X and y mean of Question 1b
X_mean = np.mean(X)
print(X_mean)

y_mean = np.mean(y)
print(y_mean)

0.47818276
0.46238747


In [ ]:
# Question 1b Solution
numerator = np.sum((X - X_mean) * (y - y_mean))
denominator = np.sum(np.square(X - X_mean))

result = numerator / denominator
result

-0.030608399

## Qs 2

Given the **`4-D`** array below:

```python
rng = np.random.default_rng(seed=5)
X = rng.random(size=(16, 3), dtype=np.float32).reshape(2, 4, 2, 3)
```

Find:

**a.** 0.1777215

**b.** 0.51532555

**c.** 


In [ ]:
# Write your solution here
# Qs 2a
rng = np.random.default_rng(seed=5)
X = rng.random(size=(16, 3), dtype=np.float32).reshape(2, 4, 2, 3)

show_array_properties(arr=X)

# 2a. axis_0, axis_1, inner axis 1, axis_2
print("The solution of 2a is:", X[1,0,1,1])

Array: 
[[[[0.67079    0.80500287 0.02265316]
   [0.8079408  0.46885186 0.51532555]]

  [[0.630234   0.28580135 0.97952366]
   [0.0539307  0.2779237  0.38336885]]

  [[0.57118434 0.4084732  0.1310609 ]
   [0.04527515 0.00101531 0.04875767]]

  [[0.14881468 0.9991761  0.19098222]
   [0.6523691  0.75025886 0.23451018]]]


 [[[0.28223735 0.43494755 0.2632376 ]
   [0.9741862  0.1777215  0.8976776 ]]

  [[0.7976888  0.844231   0.11573023]
   [0.39240462 0.62803024 0.49302298]]

  [[0.66586643 0.6766893  0.6629264 ]
   [0.0608027  0.95909935 0.5555961 ]]

  [[0.90351176 0.2714516  0.3615182 ]
   [0.8796511  0.18690258 0.06421441]]]]

Shape: (2, 4, 2, 3)
NDim: 4
Size: 48
The solution of 2a is: 0.1777215


In [ ]:
X[1]

array([[[0.28223735, 0.43494755, 0.2632376 ],
        [0.9741862 , 0.1777215 , 0.8976776 ]],

       [[0.7976888 , 0.844231  , 0.11573023],
        [0.39240462, 0.62803024, 0.49302298]],

       [[0.66586643, 0.6766893 , 0.6629264 ],
        [0.0608027 , 0.95909935, 0.5555961 ]],

       [[0.90351176, 0.2714516 , 0.3615182 ],
        [0.8796511 , 0.18690258, 0.06421441]]], dtype=float32)

In [ ]:
X[1][0]

array([[0.28223735, 0.43494755, 0.2632376 ],
       [0.9741862 , 0.1777215 , 0.8976776 ]], dtype=float32)

In [ ]:
X[1][0][1]

array([0.9741862, 0.1777215, 0.8976776], dtype=float32)

In [ ]:
X[1][0][1][1]

0.1777215

In [ ]:
# Write your solution here
# Qs 2b
rng = np.random.default_rng(seed=5)
X = rng.random(size=(16, 3), dtype=np.float32).reshape(2, 4, 2, 3)

show_array_properties(arr=X)

# Solution: axis_0, axis_1, inner axis 1, axis_2
print("The solution of 2b is:", X[0,0,1,2])


Array: 
[[[[0.67079    0.80500287 0.02265316]
   [0.8079408  0.46885186 0.51532555]]

  [[0.630234   0.28580135 0.97952366]
   [0.0539307  0.2779237  0.38336885]]

  [[0.57118434 0.4084732  0.1310609 ]
   [0.04527515 0.00101531 0.04875767]]

  [[0.14881468 0.9991761  0.19098222]
   [0.6523691  0.75025886 0.23451018]]]


 [[[0.28223735 0.43494755 0.2632376 ]
   [0.9741862  0.1777215  0.8976776 ]]

  [[0.7976888  0.844231   0.11573023]
   [0.39240462 0.62803024 0.49302298]]

  [[0.66586643 0.6766893  0.6629264 ]
   [0.0608027  0.95909935 0.5555961 ]]

  [[0.90351176 0.2714516  0.3615182 ]
   [0.8796511  0.18690258 0.06421441]]]]

Shape: (2, 4, 2, 3)
NDim: 4
Size: 48
The solution of 2b is: 0.51532555


In [ ]:
X[0]

array([[[0.67079   , 0.80500287, 0.02265316],
        [0.8079408 , 0.46885186, 0.51532555]],

       [[0.630234  , 0.28580135, 0.97952366],
        [0.0539307 , 0.2779237 , 0.38336885]],

       [[0.57118434, 0.4084732 , 0.1310609 ],
        [0.04527515, 0.00101531, 0.04875767]],

       [[0.14881468, 0.9991761 , 0.19098222],
        [0.6523691 , 0.75025886, 0.23451018]]], dtype=float32)

In [ ]:
X[0][0]

array([[0.67079   , 0.80500287, 0.02265316],
       [0.8079408 , 0.46885186, 0.51532555]], dtype=float32)

In [ ]:
X[0][0][1]

array([0.8079408 , 0.46885186, 0.51532555], dtype=float32)

In [ ]:
X[0][0][1][2]

0.51532555

## Qs 3

Using Pandas, find the number of employees that:

**a.** Write a query/code that determines the employees that are older than **30** years and their job role is either **manager** or **research director** or **manufacturing director** and have a **performance rating** greater than **3**.

**b.** Create a new column that combines `technical degree`, `other` and `human resources` from **`education field`** into a new label called **others**. i.e the resulting column should have four (4) unique labels namely: **`life sciences`**, **`medical`**, **`marketing`** and **`others`**. Hint: Use `.apply()`

**c.** Write a code that splits the data into **numerical** and **categorical** data. Display the **first 5 rows** of your results on separate cells using `.head()`. 

#### The data can be found [here](https://drive.google.com/file/d/1SSOdAGm0nCpPhKCqA1rgW00mwpseL7Dj/view?usp=share_link)

In [4]:
emp_data = pd.read_csv("HR_Employee_reduced.csv")
emp_data.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

                 JobRole  EnvironmentSatisfaction  Gender  PerformanceRating  \
0        Sales Executive                        2  Female                  3   
1     Research Scientist                        3    Male                  4   
2  Laboratory Technician                        4    Male                  3   
3     Research Scientist                        4  Female                  3   
4  Laboratory Technician                        1    Male                  3   

   HourlyRate  JobInvolvement  JobLevel  
0          94               3         2  
1          61               2         2  
2          92               2         1  
3          56               3         1  
4          40               3         1

In [5]:
emp_copy = emp_data.copy()
emp_copy.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

                 JobRole  EnvironmentSatisfaction  Gender  PerformanceRating  \
0        Sales Executive                        2  Female                  3   
1     Research Scientist                        3    Male                  4   
2  Laboratory Technician                        4    Male                  3   
3     Research Scientist                        4  Female                  3   
4  Laboratory Technician                        1    Male                  3   

   HourlyRate  JobInvolvement  JobLevel  
0          94               3         2  
1          61               2         2  
2          92               2         1  
3          56               3         1  
4          40               3         1

In [8]:
emp_copy['JobRole'].unique()

array(['Sales Executive', 'Research Scientist', 'Laboratory Technician',
       'Manufacturing Director', 'Healthcare Representative', 'Manager',
       'Sales Representative', 'Research Director', 'Human Resources'],
      dtype=object)

In [ ]:
# masking for JobRole either 'Manager', 'Research Director', 'Manufacturing Director'
mask =(emp_copy['JobRole'] == 'Manager') | ( emp_copy['JobRole'] == 'Research Director') | ( emp_copy['JobRole'] == 'Manufacturing Director')
emp_copy[mask].head()

Age Attrition     BusinessTravel  DailyRate              Department  \
8    38        No  Travel_Frequently        216  Research & Development   
15   29        No      Travel_Rarely       1389  Research & Development   
18   53        No      Travel_Rarely       1219                   Sales   
20   24        No         Non-Travel        673  Research & Development   
22   34        No      Travel_Rarely        419  Research & Development   

    DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
8                 23          3  Life Sciences              1              12   
15                21          4  Life Sciences              1              20   
18                 2          4  Life Sciences              1              23   
20                11          2          Other              1              26   
22                 7          4  Life Sciences              1              28   

                   JobRole  EnvironmentSatisfaction  Gender  \
8   Manufacturing Director                        4    Male   
15  Manufacturing Director                        2  Female   
18                 Manager                        1  Female   
20  Manufacturing Director                        1  Female   
22       Research Director                        1  Female   

    PerformanceRating  HourlyRate  JobInvolvement  JobLevel  
8                   4          44               2         3  
15                  3          51               4         3  
18                  3          78               2         4  
20                  3          96               4         2  
22                  3          53               3         3

In [ ]:
# masking for age greater than 30
age_filt = emp_copy["Age"] > 30
age_filt.head(3)

0    True
1    True
2    True
Name: Age, dtype: bool

In [ ]:
# masking for performance rate greater than 3
rate_filt = emp_copy["PerformanceRating"] > 3
rate_filt.head(3)

0    False
1     True
2    False
Name: PerformanceRating, dtype: bool

In [ ]:
# Write your solution here
# Qs 3a
filtered_data = emp_copy[(mask) & (age_filt) & (rate_filt)]
filtered_data.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
8     38        No  Travel_Frequently        216  Research & Development   
60    32        No      Travel_Rarely        427  Research & Development   
75    31        No      Travel_Rarely        746  Research & Development   
105   59        No         Non-Travel       1420         Human Resources   
135   36        No      Travel_Rarely        216  Research & Development   

     DistanceFromHome  Education   EducationField  EmployeeCount  \
8                  23          3    Life Sciences              1   
60                  1          3          Medical              1   
75                  8          4    Life Sciences              1   
105                 2          4  Human Resources              1   
135                 6          2          Medical              1   

     EmployeeNumber                 JobRole  EnvironmentSatisfaction  Gender  \
8                12  Manufacturing Director                        4    Male   
60               78  Manufacturing Director                        1    Male   
75               98  Manufacturing Director                        3  Female   
105             140                 Manager                        3  Female   
135             178  Manufacturing Director                        2    Male   

     PerformanceRating  HourlyRate  JobInvolvement  JobLevel  
8                    4          44               2         3  
60                   4          33               3         2  
75                   4          61               3         2  
105                  4          32               2         5  
135                  4          84               3         2

In [ ]:
edu = emp_copy["EducationField"].isin(['Life Sciences', 'Medical', 'Marketing', 'Others'])
edu.head()

0     True
1     True
2    False
3     True
4     True
Name: EducationField, dtype: bool

In [6]:
# Write your solution here
# Qs 3b:  Create a new column that combines technical degree, other and human resources from education field into a new label called others. 
# i.e the resulting column should have four (4) unique labels namely: life sciences, medical, marketing and others. Hint: Use .apply()
#emp_copy["Others"] = 
#emp_copy.drop(column = 'Others', axis=1)

In [7]:
emp_copy['Others'] = emp_copy['EducationField'].apply(lambda x: x if x == 'Medical' or x == 'Life Sciences' or x == 'Marketing' else 'Others' )
emp_copy.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

                 JobRole  EnvironmentSatisfaction  Gender  PerformanceRating  \
0        Sales Executive                        2  Female                  3   
1     Research Scientist                        3    Male                  4   
2  Laboratory Technician                        4    Male                  3   
3     Research Scientist                        4  Female                  3   
4  Laboratory Technician                        1    Male                  3   

   HourlyRate  JobInvolvement  JobLevel         Others  
0          94               3         2  Life Sciences  
1          61               2         2  Life Sciences  
2          92               2         1         Others  
3          56               3         1  Life Sciences  
4          40               3         1        Medical

In [8]:
emp_copy['Others'].unique()

array(['Life Sciences', 'Others', 'Medical', 'Marketing'], dtype=object)

In [18]:
# Write your solution here
# Qs 3c: Write a code that splits the data into numerical and categorical data. Display the first 5 rows of your results on separate cells using .head()
numerical_data = emp_copy.select_dtypes(include=np.number)
numerical_data.head()


Age  DailyRate  DistanceFromHome  Education  EmployeeCount  EmployeeNumber  \
0   41       1102                 1          2              1               1   
1   49        279                 8          1              1               2   
2   37       1373                 2          2              1               4   
3   33       1392                 3          4              1               5   
4   27        591                 2          1              1               7   

   EnvironmentSatisfaction  PerformanceRating  HourlyRate  JobInvolvement  \
0                        2                  3          94               3   
1                        3                  4          61               2   
2                        4                  3          92               2   
3                        4                  3          56               3   
4                        1                  3          40               3   

   JobLevel  
0         2  
1         2  
2         1  
3         1  
4         1

In [20]:
# 3c: Categorical data
Categorical_data = emp_copy.select_dtypes(include=object)
Categorical_data.head()

Attrition     BusinessTravel              Department EducationField  \
0       Yes      Travel_Rarely                   Sales  Life Sciences   
1        No  Travel_Frequently  Research & Development  Life Sciences   
2       Yes      Travel_Rarely  Research & Development          Other   
3        No  Travel_Frequently  Research & Development  Life Sciences   
4        No      Travel_Rarely  Research & Development        Medical   

                 JobRole  Gender         Others  
0        Sales Executive  Female  Life Sciences  
1     Research Scientist    Male  Life Sciences  
2  Laboratory Technician    Male         Others  
3     Research Scientist  Female  Life Sciences  
4  Laboratory Technician    Male        Medical

## Qs 4

Given the data below:

```python
salary = [74454, 54900, 76182, 56221, 81254, 75900, 67122, 62426, 61553,
       77070, 67587, 50095, 75820, 68174, 79069]
students = [
    "Sadiq",
    "Aminu",
    "Udensi",
    "Olayiwola",
    "Ukpeh",
    "Akinbade",
    "Ezeofor",
    "Oludele",
    "Gbenga",
    "Edgar",
    "Worlu",
    "Magbuwe",
    "Atte",
    "Orogun",
    "Bamigbade"
]

roles = [
    "Data Engineer",
    "Data Scientist",
    "DevOps Engineer",
    "Research Engineer",
    "Analytical Engineer",
    "Data Analyst",
    "ML Engineer",
    "DevOps Engineer",
    "Analytical Engineer",
    "Data Scientist",
    "MLOps Engineer",
    "Data Engineer",
    "Data Scientist",
    "ML Engineer",
    "Research Engineer",
]
```

**a.** Create a `DataFrame` using the lists above. The column names should be: `name` , `job_role` and `salary`.

**b.** Create a new column **`title`** that has has 2 new labels `Engineer` and `Analyst/Scientist` if the person has `engineer` or `analyst/scientist` in their job role.

**c.** What is the mean and median salary per `title`?

In [ ]:
# Question 4a sample objects
salary = [74454, 54900, 76182, 56221, 81254, 75900, 67122, 62426, 61553,
       77070, 67587, 50095, 75820, 68174, 79069]
students = [
    "Sadiq",
    "Aminu",
    "Udensi",
    "Olayiwola",
    "Ukpeh",
    "Akinbade",
    "Ezeofor",
    "Oludele",
    "Gbenga",
    "Edgar",
    "Worlu",
    "Magbuwe",
    "Atte",
    "Orogun",
    "Bamigbade"
]

roles = [
    "Data Engineer",
    "Data Scientist",
    "DevOps Engineer",
    "Research Engineer",
    "Analytical Engineer",
    "Data Analyst",
    "ML Engineer",
    "DevOps Engineer",
    "Analytical Engineer",
    "Data Scientist",
    "MLOps Engineer",
    "Data Engineer",
    "Data Scientist",
    "ML Engineer",
    "Research Engineer",
]

In [ ]:
# Write your solution here
# Qs 4a Solution
data = pd.DataFrame(
    data = {
        "name" : students,
        "job_role": roles,
        "salary" : salary
    }
            
)
data.head()

name             job_role  salary
0      Sadiq        Data Engineer   74454
1      Aminu       Data Scientist   54900
2     Udensi      DevOps Engineer   76182
3  Olayiwola    Research Engineer   56221
4      Ukpeh  Analytical Engineer   81254

In [ ]:
## 4bi. step 1
data["job_role"].unique()

array(['Data Engineer', 'Data Scientist', 'DevOps Engineer',
       'Research Engineer', 'Analytical Engineer', 'Data Analyst',
       'ML Engineer', 'MLOps Engineer'], dtype=object)

In [ ]:
## 4bii. step2
data["job_role"].str.contains("Engineer")

0      True
1     False
2      True
3      True
4      True
5     False
6      True
7      True
8      True
9     False
10     True
11     True
12    False
13     True
14     True
Name: job_role, dtype: bool

In [ ]:
# Write your solution here
# Qs 4b: Final Solutions
data["title"] =  np.where(data["job_role"].str.contains("Engineer"), "Engineer", "Analyst/Scientist")
data

name             job_role  salary              title
0       Sadiq        Data Engineer   74454           Engineer
1       Aminu       Data Scientist   54900  Analyst/Scientist
2      Udensi      DevOps Engineer   76182           Engineer
3   Olayiwola    Research Engineer   56221           Engineer
4       Ukpeh  Analytical Engineer   81254           Engineer
5    Akinbade         Data Analyst   75900  Analyst/Scientist
6     Ezeofor          ML Engineer   67122           Engineer
7     Oludele      DevOps Engineer   62426           Engineer
8      Gbenga  Analytical Engineer   61553           Engineer
9       Edgar       Data Scientist   77070  Analyst/Scientist
10      Worlu       MLOps Engineer   67587           Engineer
11    Magbuwe        Data Engineer   50095           Engineer
12       Atte       Data Scientist   75820  Analyst/Scientist
13     Orogun          ML Engineer   68174           Engineer
14  Bamigbade    Research Engineer   79069           Engineer

In [ ]:
# Write your solution here
# Qs 4c
data.pivot_table(index='title', aggfunc=([np.mean, np.median]))

mean median
                         salary salary
title                                 
Analyst/Scientist  70922.500000  75860
Engineer           67648.818182  67587

In [ ]:
# OR 4C
pd.pivot_table(data=data, index='title', aggfunc=[np.mean, np.median], margins =True)

mean median
                         salary salary
title                                 
Analyst/Scientist  70922.500000  75860
Engineer           67648.818182  67587
All                68521.800000  68174